# User config
author: "임재형"
tagline: ""
description: "1993 6 4 새로운 것에 대한 호기심과 과감하게 도전하는 추진력으로 다양한 경험과 배움을 추구하는 '임재형'입니다."
url: "htps://LIM-jaehyung.github.io"
keywords: "Actor, Singer"
email: "act_limjaehyung@naver.com"
instagram: "https://www.instagram.com/fooood_jh/"
blog: "https://blog.naver.com/act_limjaehyung"
youtube: "https://www.youtube.com/channel/UCgd9DtE-Br6EIcppEH5GfBw"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed